server:
  port: 8088
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/qf?serverTimezone=UTC
      username: root
      password: 456123
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yg.j1902.pojo
